# Mineral composition analysis system (XRD)
## Konju National University: Ju Young Park(leahlove6786@gmail.com), Hongkeun Jin.

### 1. Importing Modules

In [1]:
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d
from sklearn.cluster import KMeans 
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.models import load_model              
import joblib
import warnings

### 2. Data loading

In [2]:
# XRD intensity profile (.csv)
data=pd.read_csv('XRD_weight_change.csv')
X_all=data.iloc[:,13:] 
Y_all=data[["Quartz","Albite", "Opal-A", "Calcite", "Muscovite", "Dolomite", "Chlorite", "Kaolinite", "Illite", "Pyrite", "NaCl","K-feldspar"]];
X_all.shape, Y_all.shape

((488, 3100), (488, 12))

### 3. Data preprocessing
#### 3-1. Sample-based preprocessing (Min-Max scaler)

In [3]:
X_all_T=X_all.T

# MinMaxscaler
df_scale = pd.DataFrame(MinMaxScaler().fit_transform(X_all_T), columns=X_all_T.columns, index = X_all_T.index)

df_scale_T=df_scale.T
df_scale_T.shape

(488, 3100)

#### 3-2. Data split

In [4]:
# split testset
seed = 0
X_tr_val, X_te, Y_tr_val, Y_te = train_test_split(X_all, Y_all, test_size=0.1, random_state=seed)
X_tr_val.shape, X_te.shape, Y_tr_val.shape, Y_te.shape

((439, 3100), (49, 3100), (439, 12), (49, 12))

### 4. Clustering

In [5]:
k = 5
model = KMeans(n_clusters = k, init='k-means++', n_init=100, max_iter=500, tol=1e-04,random_state = 0)

model.fit(X_tr_val)

KMeans(max_iter=500, n_clusters=5, n_init=100, random_state=0)

In [6]:
# Create a DataFrame to store sample numbers and clustering results
clustering_data = pd.DataFrame({'Sample number': range(X_te.shape[0])})

clustering_data['cluster']=model.predict(X_te)

# Changing cluster labels from 0-4 to 1-5
clustering_data['cluster']=clustering_data['cluster']+1

# Expert analysis(0): Cluster 1, 2, 5
# Machine learning analysis(1): Cluster 3, 4
clustering_data['analysis']=clustering_data['cluster'].apply(lambda x: 0 if x in [1, 2, 5] else (1 if x in [3, 4] else None))

# Export to clustering results
df = pd.concat([clustering_data.reset_index(drop=True), X_te.reset_index(drop=True)], axis=1)
df.to_csv('Clustering results_test.csv')
df

,Sample number,cluster,analysis,Angle3.01,Angle3.03,Angle,Angle.1,Angle.2,Angle.3,Angle.4,...,Angle.3088,Angle.3089,Angle.3090,Angle.3091,Angle.3092,Angle.3093,Angle.3094,Angle.3095,Angle64.97,Angle64.99
0,0,4,1,1.520000,41.370000,20.220000,16.070000,-12.080000,-13.230000,3.620000,...,5.036842,-10.968421,2.026316,2.021053,1.015789,6.010526,13.005263,-1.000000,2.000000,1.00
1,1,1,0,2.886080,-3.703693,-1.793466,1.116761,5.026989,-0.062784,-0.652557,...,-0.491445,1.007375,-0.493805,0.505015,-1.996165,0.502655,-0.998525,-0.499705,-1.000000,3.50
2,2,4,1,1.000000,-7.222222,29.555556,4.333333,3.111111,-16.111111,-11.333333,...,7.072464,8.057971,3.043478,-10.971015,2.014493,-2.000000,-2.000000,0.000000,-7.000000,3.00
3,3,4,1,-8.181818,-14.090909,14.000000,-9.909091,5.181818,10.272727,1.363636,...,1.039726,-5.964688,0.030898,5.026484,1.022070,0.017656,2.013242,-0.991172,0.004414,0.00
4,4,5,0,-5.120000,3.410000,15.940000,-17.530000,-25.000000,-22.470000,10.060000,...,-9.980226,-4.983051,4.014124,4.011299,5.008475,-7.994350,-4.997175,4.000000,11.000000,4.00
5,5,1,0,6.511923,1.490385,3.468846,-0.052692,14.925769,-5.095769,-7.117308,...,-1.500000,1.500000,3.000000,1.000000,-1.000000,0.000000,1.500000,1.500000,4.500000,1.50
6,6,4,1,-10.000000,2.652308,15.304615,19.956923,-16.390769,6.261539,-3.086154,...,-0.920755,-4.929560,-3.938365,-0.947170,-1.955975,6.035220,1.026415,-1.982390,2.008805,5.00
7,7,4,1,6.000000,19.816667,9.633333,-8.550000,-17.733333,6.083333,13.900000,...,6.973451,2.976401,4.979351,0.982301,4.985251,7.988201,9.991150,-0.005900,-2.002950,5.00
8,8,2,0,8.043478,1.282609,-6.478261,5.760870,-33.000000,23.239130,4.478261,...,3.059524,6.047619,4.035714,1.023810,-1.988095,0.000000,1.000000,4.000000,-1.000000,1.00
9,9,4,1,-8.900000,5.550000,8.000000,13.450000,12.900000,-2.650000,11.800000,...,0.056497,3.045198,4.033898,2.022599,0.011299,0.000000,-5.000000,3.000000,-5.000000,-3.00
10,10,4,1,-5.229091,11.385454,-13.000000,5.614546,-12.770909,-5.156364,-20.541818,...,-4.957640,-3.963691,1.030257,9.024206,2.018154,-2.987897,-2.993949,1.000000,1.000000,-2.00
11,11,3,1,-1.501818,-12.250909,-7.000000,-18.749091,7.501818,-5.247273,7.003636,...,14.136364,-0.890909,-1.918182,0.054545,4.027273,5.000000,5.000000,-2.000000,4.000000,4.00
12,12,1,0,-11.809091,5.954545,8.218182,-0.518182,1.245455,2.009091,4.772727,...,-0.490210,-0.991560,0.507089,0.505739,1.004389,0.503038,0.001688,3.000338,0.500000,2.50
13,13,2,0,-5.978182,4.510909,-8.000000,-11.510909,-17.021818,3.467273,-9.043636,...,-1.927298,-2.935376,-0.943454,-4.951532,-0.959610,5.032312,5.024234,-3.983844,-2.991922,3.00
14,14,4,1,4.520000,18.260000,-20.000000,-13.260000,-5.520000,-14.780000,5.960000,...,2.019337,3.016575,1.013812,4.011050,-4.991713,0.005525,4.002762,2.000000,10.000000,1.00
15,15,4,1,16.000000,-6.176154,-21.352308,-15.528462,19.295385,3.119231,-26.056923,...,9.080718,-2.928251,8.062780,2.053812,-4.955157,2.035874,-1.973094,4.017937,3.008969,7.00
16,16,2,0,16.019500,11.058000,26.096500,35.135000,-2.826500,-3.788000,34.250500,...,2.600000,-1.400000,-4.400000,7.600000,3.600000,0.600000,2.600000,-1.400000,0.600000,-3.40
17,17,4,1,23.932857,12.985714,8.038571,-13.908571,-9.855714,2.197143,-2.750000,...,5.036596,-0.967470,11.028464,1.024398,-0.979669,1.016265,7.012199,11.008133,-4.995934,8.00
18,18,1,0,-0.902143,5.189286,-1.219286,8.872143,-9.536429,3.555000,-0.853571,...,3.500000,0.500000,4.500000,2.000000,2.500000,4.000000,-2.000000,2.500000,-0.500000,3.00
19,19,1,0,0.489091,-0.012727,5.485455,-8.016364,-2.018182,4.480000,2.978182,...,0.527885,2.024038,0.520192,1.016346,1.512500,2.508654,1.004808,-0.999038,1.000000,4.00
20,20,1,0,-9.697368,0.986842,-0.828947,3.355263,5.039474,3.723684,-3.592105,...,0.526079,2.022482,2.518885,-0.984712,1.511691,-0.491907,2.504496,2.500899,-1.500000,1.50
21,21,1,0,-0.975000,-4.419000,-0.363000,-5.807000,-3.251000,-1.695000,1.861000,...,2.000216,1.000000,0.500000,3.000000,-0.500000,0.000000,2.500000,4.000000,3.500000,-0.50
22,22,1,0,-0.352254,-7.340525,-5.328797,-8.317069,-1.305341,-8.793612,8.718116,...,5.424156,3.925269,5.426382,5.927495,1.428608,7.429722,5.430000,4.930000,10.430000,9.93
23,23,2,0,0.604286,-6.171429,23.052857,7.277143,14.501429,1.725714,2.950000,...,9.204202,10.181513,3.158824,0.136134,-6.886555,0.090756,8.068067,0.045378,1.022689,4.00
24,24,1,0,-8.587500,9.779300,-9.853900,-2.987100,8.379700,-6.753500,0.613300,...,1.000000,6.500000,1.500000,-1.000000,-1.000000,-1.000000,2.500000,1.000000,2.500000,-1.00
25,25,1,0,-7.277143,-6.200000,-11.622857,8.954286,3.031429,-4.391429,2.685714,...,1.001656,4.501341,2.001025,1.500710,3.000394,-0.499921,3.000000,5.000000,0.000000,3.50
26,26,1,0,12.651970,-5.019545,4.808939,-9.362576,-4.034091,1.294394,-5.377121,...,-1.493269,3.505449,-1.995833,3.502885,-2.498397,-0.999680,1.000000,0.000000,0.500000,1.50
27,27,1,0,1.047685,-0.152685,-3.353056,-7.553426,3.246204,0.545833,0.845463,...,0.696500,0.198500,0.200000,-0.300000,-0.800000,3.700000,0.700000,-0.300000,2.700000,2.20
28,28,4,1,-2.893617,-1.744681,2.404255,-20.446808,-5.297872,-4.148936,4.000000,...,1.000000,6.000000,1.000000,2.000000,-1.000000,1.000000,1.000000,-9.000000,1.000000,5.00
29,29,3,1,11.698571,-13.622857,-5.944286,-15.265714,24.412857,5.091429,-6.230000,...,-0.889435,11.098280,7.085995,4.073710,3.061425,4.049140,-7.963145,5.024570,-3.987715,-1.00
30,30,1,0,1.226667,-4.460000,-11.646667,2.666667,-3.020000,0.793333,-9.893333,...,-1.297484,2.700000,0.200000,2.700000,1.700000,1.700000,1.700000,0.700000,-1.300000,1.70
31,31,4,1,-4.211905,27.232857,-10.322381,0.122381,17.567143,7.011905,-22.543333,...,-3.015106,1.987915,4.990937,-0.006042,-3.003021,-1.000000,7.000000,3.000000,5.000000,-2.00
32,32,1,0,3.777778,12.976190,3.174603,9.373016,0.571429,-1.730159,13.468254,...,-2.979137,0.017986,-0.984892,-1.987770,0.009352,4.506475,1.503597,-0.499281,2.000000,1.00
33,33,4,1,11.000000,-6.655714,-11.311429,15.032857,13.377143,9.721429,19.065714,...,1.247826,12.220290,11.192754,2.165217,-2.862319,-1.889855,-2.917391,-4.944928,8.027536,-3.00
34,34,4,1,11.553333,16.355238,6.157143,10.959048,3.760952,41.562857,-0.635238,...,10.064815,0.055556,3.046296,5.037037,-3.972222,2.018518,4.009259,-1.000000,-8.000000,-2.00
35,35,1,0,0.276000,-14.728000,3.768000,3.764000,-2.240000,1.756000,6.252000,...,-0.478863,1.018222,-0.984694,-0.487609,1.509475,-0.993440,-1.496356,-2.499271,0.500000,2.00
36,36,1,0,-7.695870,-1.234130,4.227609,-1.810652,-4.848913,6.112826,2.074565,...,0.702143,-0.298810,-1.299762,1.700000,1.200000,2.200000,0.700000,1.200000,0.700000,0.20
37,37,1,0,2.614152,-2.217712,0.450424,-7.381441,-1.713305,-2.545170,3.122966,...,-0.407447,1.579787,-0.932979,2.054255,1.041489,-1.971277,3.015957,0.003191,0.000000,1.00
38,38,1,0,1.659574,4.425532,0.191489,-5.042553,4.223404,3.989362,-13.244681,...,8.860667,3.349111,0.337556,1.826000,-1.685556,0.302889,1.300000,0.300000,-0.200000,-1.20
39,39,1,0,0.514286,-6.522857,-7.060000,-5.097143,-5.134286,6.328571,-7.708571,...,1.535064,7.030228,0.025391,5.520555,3.015718,0.010882,2.506045,5.501209,1.000000,0.50
40,40,3,1,4.815000,-2.090000,7.005000,-19.900000,1.195000,7.290000,-6.615000,...,1.516997,9.508499,-1.500000,-3.500000,1.500000,-5.500000,-0.500000,-3.500000,-4.500000,1.50
41,41,2,0,-5.197143,15.975714,14.148571,30.321429,-16.505714,0.667143,-3.160000,...,4.168750,8.150000,2.131250,-0.887500,5.093750,12.075000,-4.943750,-0.962500,5.018750,0.00
42,42,1,0,-4.932368,-11.860789,-5.789211,11.782368,4.853947,-4.074474,4.497105,...,-0.500000,2.000000,-2.000000,0.500000,1.000000,-2.500000,0.000000,-2.000000,1.500000,0.00
43,43,4,1,5.057000,9.188000,10.319000,22.450000,15.581000,10.712000,6.843000,...,1.061584,3.052786,-4.956012,3.035191,-4.973607,1.017595,0.008798,8.000000,2.000000,-2.00
44,44,1,0,-8.640000,14.660000,-0.040000,-3.740000,-4.440000,7.360000,-7.840000,...,1.918079,1.929379,-0.559322,0.951977,0.963277,0.474576,-0.014124,1.997175,-0.500000,1.00
45,45,4,1,-7.000000,11.637692,2.275385,-10.086923,-2.449231,1.188462,-10.173846,...,-6.955056,10.035955,-7.973034,-0.982023,-1.991011,7.000000,1.000000,2.000000,5.000000,3.00
46,46,2,0,-10.510454,-1.082727,0.345000,4.772727,-24.799546,13.628182,-1.944091,...,5.048348,1.041441,-3.965466,6.027628,5.020721,-3.986186,-4.993093,-2.000000,0.000000,3.00
47,47,4,1,18.244444,-13.316667,-16.877778,-38.438889,5.000000,-1.561111,-11.122222,...,-1.947214,1.046921,0.041056,3.035191,-3.970674,-2.976540,8.017595,6.011730,2.005865,-3.00
48,48,1,0,10.847143,1.050000,1.252857,-1.544286,-4.841429,3.361429,-0.935714,...,3.021106,0.517085,-1.986935,-1.990955,0.505025,-0.498995,2.000000,2.000000,1.000000,-3.00

### 5. Mineral composition analysis

### 5-1. Expert group

In [7]:
df_analysis_0 = df[df['analysis'] == 0]
df_analysis_0.to_csv('Analysis by expert.csv', index=False)
df_analysis_0

,Sample number,cluster,analysis,Angle3.01,Angle3.03,Angle,Angle.1,Angle.2,Angle.3,Angle.4,...,Angle.3088,Angle.3089,Angle.3090,Angle.3091,Angle.3092,Angle.3093,Angle.3094,Angle.3095,Angle64.97,Angle64.99
1,1,1,0,2.886080,-3.703693,-1.793466,1.116761,5.026989,-0.062784,-0.652557,...,-0.491445,1.007375,-0.493805,0.505015,-1.996165,0.502655,-0.998525,-0.499705,-1.000000,3.50
4,4,5,0,-5.120000,3.410000,15.940000,-17.530000,-25.000000,-22.470000,10.060000,...,-9.980226,-4.983051,4.014124,4.011299,5.008475,-7.994350,-4.997175,4.000000,11.000000,4.00
5,5,1,0,6.511923,1.490385,3.468846,-0.052692,14.925769,-5.095769,-7.117308,...,-1.500000,1.500000,3.000000,1.000000,-1.000000,0.000000,1.500000,1.500000,4.500000,1.50
8,8,2,0,8.043478,1.282609,-6.478261,5.760870,-33.000000,23.239130,4.478261,...,3.059524,6.047619,4.035714,1.023810,-1.988095,0.000000,1.000000,4.000000,-1.000000,1.00
12,12,1,0,-11.809091,5.954545,8.218182,-0.518182,1.245455,2.009091,4.772727,...,-0.490210,-0.991560,0.507089,0.505739,1.004389,0.503038,0.001688,3.000338,0.500000,2.50
13,13,2,0,-5.978182,4.510909,-8.000000,-11.510909,-17.021818,3.467273,-9.043636,...,-1.927298,-2.935376,-0.943454,-4.951532,-0.959610,5.032312,5.024234,-3.983844,-2.991922,3.00
16,16,2,0,16.019500,11.058000,26.096500,35.135000,-2.826500,-3.788000,34.250500,...,2.600000,-1.400000,-4.400000,7.600000,3.600000,0.600000,2.600000,-1.400000,0.600000,-3.40
18,18,1,0,-0.902143,5.189286,-1.219286,8.872143,-9.536429,3.555000,-0.853571,...,3.500000,0.500000,4.500000,2.000000,2.500000,4.000000,-2.000000,2.500000,-0.500000,3.00
19,19,1,0,0.489091,-0.012727,5.485455,-8.016364,-2.018182,4.480000,2.978182,...,0.527885,2.024038,0.520192,1.016346,1.512500,2.508654,1.004808,-0.999038,1.000000,4.00
20,20,1,0,-9.697368,0.986842,-0.828947,3.355263,5.039474,3.723684,-3.592105,...,0.526079,2.022482,2.518885,-0.984712,1.511691,-0.491907,2.504496,2.500899,-1.500000,1.50
21,21,1,0,-0.975000,-4.419000,-0.363000,-5.807000,-3.251000,-1.695000,1.861000,...,2.000216,1.000000,0.500000,3.000000,-0.500000,0.000000,2.500000,4.000000,3.500000,-0.50
22,22,1,0,-0.352254,-7.340525,-5.328797,-8.317069,-1.305341,-8.793612,8.718116,...,5.424156,3.925269,5.426382,5.927495,1.428608,7.429722,5.430000,4.930000,10.430000,9.93
23,23,2,0,0.604286,-6.171429,23.052857,7.277143,14.501429,1.725714,2.950000,...,9.204202,10.181513,3.158824,0.136134,-6.886555,0.090756,8.068067,0.045378,1.022689,4.00
24,24,1,0,-8.587500,9.779300,-9.853900,-2.987100,8.379700,-6.753500,0.613300,...,1.000000,6.500000,1.500000,-1.000000,-1.000000,-1.000000,2.500000,1.000000,2.500000,-1.00
25,25,1,0,-7.277143,-6.200000,-11.622857,8.954286,3.031429,-4.391429,2.685714,...,1.001656,4.501341,2.001025,1.500710,3.000394,-0.499921,3.000000,5.000000,0.000000,3.50
26,26,1,0,12.651970,-5.019545,4.808939,-9.362576,-4.034091,1.294394,-5.377121,...,-1.493269,3.505449,-1.995833,3.502885,-2.498397,-0.999680,1.000000,0.000000,0.500000,1.50
27,27,1,0,1.047685,-0.152685,-3.353056,-7.553426,3.246204,0.545833,0.845463,...,0.696500,0.198500,0.200000,-0.300000,-0.800000,3.700000,0.700000,-0.300000,2.700000,2.20
30,30,1,0,1.226667,-4.460000,-11.646667,2.666667,-3.020000,0.793333,-9.893333,...,-1.297484,2.700000,0.200000,2.700000,1.700000,1.700000,1.700000,0.700000,-1.300000,1.70
32,32,1,0,3.777778,12.976190,3.174603,9.373016,0.571429,-1.730159,13.468254,...,-2.979137,0.017986,-0.984892,-1.987770,0.009352,4.506475,1.503597,-0.499281,2.000000,1.00
35,35,1,0,0.276000,-14.728000,3.768000,3.764000,-2.240000,1.756000,6.252000,...,-0.478863,1.018222,-0.984694,-0.487609,1.509475,-0.993440,-1.496356,-2.499271,0.500000,2.00
36,36,1,0,-7.695870,-1.234130,4.227609,-1.810652,-4.848913,6.112826,2.074565,...,0.702143,-0.298810,-1.299762,1.700000,1.200000,2.200000,0.700000,1.200000,0.700000,0.20
37,37,1,0,2.614152,-2.217712,0.450424,-7.381441,-1.713305,-2.545170,3.122966,...,-0.407447,1.579787,-0.932979,2.054255,1.041489,-1.971277,3.015957,0.003191,0.000000,1.00
38,38,1,0,1.659574,4.425532,0.191489,-5.042553,4.223404,3.989362,-13.244681,...,8.860667,3.349111,0.337556,1.826000,-1.685556,0.302889,1.300000,0.300000,-0.200000,-1.20
39,39,1,0,0.514286,-6.522857,-7.060000,-5.097143,-5.134286,6.328571,-7.708571,...,1.535064,7.030228,0.025391,5.520555,3.015718,0.010882,2.506045,5.501209,1.000000,0.50
41,41,2,0,-5.197143,15.975714,14.148571,30.321429,-16.505714,0.667143,-3.160000,...,4.168750,8.150000,2.131250,-0.887500,5.093750,12.075000,-4.943750,-0.962500,5.018750,0.00
42,42,1,0,-4.932368,-11.860789,-5.789211,11.782368,4.853947,-4.074474,4.497105,...,-0.500000,2.000000,-2.000000,0.500000,1.000000,-2.500000,0.000000,-2.000000,1.500000,0.00
44,44,1,0,-8.640000,14.660000,-0.040000,-3.740000,-4.440000,7.360000,-7.840000,...,1.918079,1.929379,-0.559322,0.951977,0.963277,0.474576,-0.014124,1.997175,-0.500000,1.00
46,46,2,0,-10.510454,-1.082727,0.345000,4.772727,-24.799546,13.628182,-1.944091,...,5.048348,1.041441,-3.965466,6.027628,5.020721,-3.986186,-4.993093,-2.000000,0.000000,3.00
48,48,1,0,10.847143,1.050000,1.252857,-1.544286,-4.841429,3.361429,-0.935714,...,3.021106,0.517085,-1.986935,-1.990955,0.505025,-0.498995,2.000000,2.000000,1.000000,-3.00

#### 5-2. Machine learning group

In [8]:
df_analysis_1= pd.concat([clustering_data.reset_index(drop=True), X_te.reset_index(drop=True)], axis=1)
df_analysis_1 = df_analysis_1[df_analysis_1['analysis'] == 1]

# export to intensity profile
df_analysis_x=df_analysis_1.iloc[:,3:3104]
df_analysis_x

,Angle3.01,Angle3.03,Angle,Angle.1,Angle.2,Angle.3,Angle.4,Angle.5,Angle.6,Angle.7,...,Angle.3088,Angle.3089,Angle.3090,Angle.3091,Angle.3092,Angle.3093,Angle.3094,Angle.3095,Angle64.97,Angle64.99
0,1.520000,41.370000,20.220000,16.070000,-12.080000,-13.230000,3.620000,-6.530000,4.320000,-2.830000,...,5.036842,-10.968421,2.026316,2.021053,1.015789,6.010526,13.005263,-1.000000,2.000000,1.0
2,1.000000,-7.222222,29.555556,4.333333,3.111111,-16.111111,-11.333333,-9.555556,-7.777778,-14.000000,...,7.072464,8.057971,3.043478,-10.971015,2.014493,-2.000000,-2.000000,0.000000,-7.000000,3.0
3,-8.181818,-14.090909,14.000000,-9.909091,5.181818,10.272727,1.363636,8.454546,-1.454546,5.636364,...,1.039726,-5.964688,0.030898,5.026484,1.022070,0.017656,2.013242,-0.991172,0.004414,0.0
6,-10.000000,2.652308,15.304615,19.956923,-16.390769,6.261539,-3.086154,-16.433846,-14.781538,-8.129231,...,-0.920755,-4.929560,-3.938365,-0.947170,-1.955975,6.035220,1.026415,-1.982390,2.008805,5.0
7,6.000000,19.816667,9.633333,-8.550000,-17.733333,6.083333,13.900000,-10.283333,-2.466667,22.350000,...,6.973451,2.976401,4.979351,0.982301,4.985251,7.988201,9.991150,-0.005900,-2.002950,5.0
9,-8.900000,5.550000,8.000000,13.450000,12.900000,-2.650000,11.800000,-22.750000,31.700000,-9.850000,...,0.056497,3.045198,4.033898,2.022599,0.011299,0.000000,-5.000000,3.000000,-5.000000,-3.0
10,-5.229091,11.385454,-13.000000,5.614546,-12.770909,-5.156364,-20.541818,21.072727,19.687273,-7.698182,...,-4.957640,-3.963691,1.030257,9.024206,2.018154,-2.987897,-2.993949,1.000000,1.000000,-2.0
11,-1.501818,-12.250909,-7.000000,-18.749091,7.501818,-5.247273,7.003636,-16.745455,-0.494546,8.756364,...,14.136364,-0.890909,-1.918182,0.054545,4.027273,5.000000,5.000000,-2.000000,4.000000,4.0
14,4.520000,18.260000,-20.000000,-13.260000,-5.520000,-14.780000,5.960000,-27.300000,1.440000,-15.820000,...,2.019337,3.016575,1.013812,4.011050,-4.991713,0.005525,4.002762,2.000000,10.000000,1.0
15,16.000000,-6.176154,-21.352308,-15.528462,19.295385,3.119231,-26.056923,1.766923,-5.409231,14.414615,...,9.080718,-2.928251,8.062780,2.053812,-4.955157,2.035874,-1.973094,4.017937,3.008969,7.0
17,23.932857,12.985714,8.038571,-13.908571,-9.855714,2.197143,-2.750000,-12.697143,5.355714,36.408571,...,5.036596,-0.967470,11.028464,1.024398,-0.979669,1.016265,7.012199,11.008133,-4.995934,8.0
28,-2.893617,-1.744681,2.404255,-20.446808,-5.297872,-4.148936,4.000000,-13.851064,-0.702128,12.446808,...,1.000000,6.000000,1.000000,2.000000,-1.000000,1.000000,1.000000,-9.000000,1.000000,5.0
29,11.698571,-13.622857,-5.944286,-15.265714,24.412857,5.091429,-6.230000,13.448571,9.127143,-1.194286,...,-0.889435,11.098280,7.085995,4.073710,3.061425,4.049140,-7.963145,5.024570,-3.987715,-1.0
31,-4.211905,27.232857,-10.322381,0.122381,17.567143,7.011905,-22.543333,21.901429,-7.653810,-15.209048,...,-3.015106,1.987915,4.990937,-0.006042,-3.003021,-1.000000,7.000000,3.000000,5.000000,-2.0
33,11.000000,-6.655714,-11.311429,15.032857,13.377143,9.721429,19.065714,-20.590000,-13.245714,1.098571,...,1.247826,12.220290,11.192754,2.165217,-2.862319,-1.889855,-2.917391,-4.944928,8.027536,-3.0
34,11.553333,16.355238,6.157143,10.959048,3.760952,41.562857,-0.635238,3.166667,-11.031429,24.770476,...,10.064815,0.055556,3.046296,5.037037,-3.972222,2.018518,4.009259,-1.000000,-8.000000,-2.0
40,4.815000,-2.090000,7.005000,-19.900000,1.195000,7.290000,-6.615000,-5.520000,-19.425000,-3.330000,...,1.516997,9.508499,-1.500000,-3.500000,1.500000,-5.500000,-0.500000,-3.500000,-4.500000,1.5
43,5.057000,9.188000,10.319000,22.450000,15.581000,10.712000,6.843000,-16.026000,-4.895000,-0.764000,...,1.061584,3.052786,-4.956012,3.035191,-4.973607,1.017595,0.008798,8.000000,2.000000,-2.0
45,-7.000000,11.637692,2.275385,-10.086923,-2.449231,1.188462,-10.173846,-3.536154,14.101539,-15.260769,...,-6.955056,10.035955,-7.973034,-0.982023,-1.991011,7.000000,1.000000,2.000000,5.000000,3.0
47,18.244444,-13.316667,-16.877778,-38.438889,5.000000,-1.561111,-11.122222,6.316667,15.755556,-21.805556,...,-1.947214,1.046921,0.041056,3.035191,-3.970674,-2.976540,8.017595,6.011730,2.005865,-3.0

In [9]:
composition_model=load_model('./CNN_model_minmax/')

WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.

In [10]:
composition_model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv1d_18 (Conv1D)          (None, 3051, 32)          1632

 max_pooling1d_18 (MaxPoolin  (None, 762, 32)          0
 g1D)

 conv1d_19 (Conv1D)          (None, 713, 64)           102464

 max_pooling1d_19 (MaxPoolin  (None, 178, 64)          0
 g1D)

 conv1d_20 (Conv1D)          (None, 129, 128)          409728

 max_pooling1d_20 (MaxPoolin  (None, 32, 128)          0
 g1D)

 flatten_7 (Flatten)         (None, 4096)              0

 dense_43 (Dense)            (None, 100)               409700

 dense_44 (Dense)            (None, 12)                1212

=================================================================
Total params: 924,736
Trainable params: 924,736
Non-trainable params: 0
_________________________________________________________________

In [11]:
X_scaled_3D = df_analysis_x.values.reshape(df_analysis_x.values.shape[0], df_analysis_x.values.shape[1], 1)

Y_predicted=composition_model.predict(X_te)
CNN_predict = pd.DataFrame(Y_te)
round(CNN_predict.describe().T,2)

2/2 [==============================] - 0s 31ms/step

            count   mean    std  min   25%   50%   75%   max
Quartz       49.0  19.06   9.65  8.1  13.2  16.3  19.0  54.1
Albite       49.0   9.94   5.39  3.3   7.3   8.6  10.3  33.7
Opal-A       49.0  29.21  12.15  0.0  24.7  29.5  36.5  57.5
Calcite      49.0   4.48   7.20  0.0   0.0   2.4   6.0  45.0
Muscovite    49.0  10.81   2.49  4.4   9.4  11.0  12.2  17.6
Dolomite     49.0   0.03   0.21  0.0   0.0   0.0   0.0   1.5
Chlorite     49.0   3.57   1.07  1.1   2.9   3.6   4.3   6.0
Kaolinite    49.0   1.67   0.63  0.0   1.3   1.6   2.1   3.1
Illite       49.0  10.56   2.80  2.2   9.1  11.0  12.4  15.8
Pyrite       49.0   2.68   1.26  0.0   2.1   2.5   3.1   5.7
NaCl         49.0   1.39   0.87  0.0   1.0   1.5   2.1   3.0
K-feldspar   49.0   6.60   1.89  3.1   5.2   6.4   7.8  11.4

In [12]:
CNN_predict.to_csv('Analysis by ML.csv')

## End of codes